### ISSUE TITLE
code-editor-type field not displaying on standalone version of theme

### ISSUE THREAD

**Issue by brettshumaker** [parallelus/Runway-Framework#136] opened 2015-05-06 14:10 UTC
Noticing an issue where a code-editor-type field works properly on a child theme of Runway, but fails to display on a standalone version of that theme. The data from that field is in the database, the field just isn't displaying.

Let me know if you need any more info from me.

![child-theme](https://cloud.githubusercontent.com/assets/1558827/7493742/fe8267ec-f3c8-11e4-9255-6696bbb12a8f.png)
From the child theme

![standalone](https://cloud.githubusercontent.com/assets/1558827/7493743/fe8394e6-f3c8-11e4-8335-67e3abe95c6b.png)
From the stand alone theme

**Comment by brettshumaker** [comment] 2015-05-12 20:57
Hey @parallelus - Any ideas on this yet?

Thanks!

**Comment by parallelus** [comment] 2015-05-14 15:30
Testing this now.

**Comment by parallelus** [comment] 2015-05-14 18:01
Not sure what's happening but I'm able to replicate it. Didn't find a fix yet. We will have a look at this in more detail to figure it out and get a fix released.

**Comment by brettshumaker** [comment] 2015-05-14 18:15
Thanks, Andy. I'll keep an eye out for the release.

**Comment by lesninsky** [comment] 2015-05-18 14:34
I have downloaded Runway-Framework from develop branch, created and saved in child theme the option page with code-editor element, created a standalone theme from the child one, downloaded and deployed it on 2 sites (regular one and network install) - it works properly. Perhaps there are any limitations in .httaccess for access to files or any other details, which will allow to reproduce this issue?

**Comment by parallelus** [comment] 2015-05-18 15:04
I was able to replicate this using the new Go Explore! theme. Maybe we can pinpoint something in there specific to this issue. I'm guessing this is happening on the 'develop' branch only. It seems that it worked in the latest release so it's likely a recent change that was made. I know that Go Explore! was made with 'develop' and I believe that Brett is also running off a version from 'develop' too.

@lesninsky  Try pulling the Go Explore! repo and create a code editor with that. I did replicate it that way. If that doesn't work, I'll setup something for you on an environment where I can create the same conditions. 

Thanks for checking into this. Runway is getting better every day!

**Comment by lesninsky** [comment] 2015-05-19 13:30
I still can not reproduce the issue with the version from Go Explore! repo. Please note that I have done Rebuild Download Package before downloading the standalone theme. Could you please check are there any messages in the browser's debug console and please clarify upon what conditions this issue is arising.

**Comment by parallelus** [comment] 2015-05-19 21:02
I'm going to be testing this some more today. I'm adding a field for a code editor into a theme now so I will have a good test case. I'll post back with any issues.

**Comment by parallelus** [comment] 2015-05-20 04:57
I've just tested it again, and it worked. I'm not sure what might have been done differently this time, but the code editor is showing up in the standalone theme.

The only difference I'm aware of is I added some test content to the editor before generating the standalone theme. 

One thing to check. Make sure the standalone version includes the folder 'framework/includes/themes-manager'. This was a change in a recent update making this folder a included because of some required code in the extension.

**Comment by lesninsky** [comment] 2015-05-20 14:05
This also works with blank field content.

**Comment by parallelus** [comment] 2015-05-20 15:20
@brettshumaker 

I think we're going to need to look more specifically at your case. Check on that "themes-manager" folder as a place to start.

**Comment by brettshumaker** [comment] 2015-05-22 15:04
@parallelus 'framework/includes/themes-manager' is included in our standalone theme

**Comment by parallelus** [comment] 2015-05-22 17:30
I should probably take a closer look at this. Send me the theme or if there
is server details for me to access the code and dev site. I suppose it's
some thing specific to the use case but better to find it and if possible
update Runway so it won't happen to anyone else.

**Comment by brettshumaker** [comment] 2015-05-22 19:26
Emailed you with download links.

**Comment by parallelus** [comment] 2015-05-26 19:53
You mentioned that when you updated your most recent copy of the theme to the Runway develop branch the code editor started working. Do we need to investigate this specific issue still or can it be closed?

**Comment by brettshumaker** [comment] 2015-05-26 19:57
Correct. Only investigate it if you want to try to figure out what was causing it, otherwise close it.

Thanks!

**Comment by parallelus** [comment] 2015-05-26 20:00
I have the files and I'm going to dig around in them to see if there is an obvious issue. If so, we might have previously fixed it. I'd like to determine that for sure so I'm going to work on that now and if I don't find anything, since the code is now working, I will close this afterwards.

Thanks!

**Closed** 2015-06-15 20:43 UTC
Labels: bug, Priority 1: High
